/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// EmbedSpecApplyConfiguration represents a declarative configuration of the EmbedSpec type for use
// with apply.
//
// EmbedSpec configures Discord's native embed rendering (the colored
// "bubble" with title, description, thumbnail, author and footer) instead
// of a plain text message.
type EmbedSpecApplyConfiguration struct {
	// enabled switches a feed's messages from plain text content to a
	// Discord embed.
	Enabled *bool `json:"enabled,omitempty"`
	// color is the embed's side-bar color, as a hex string (e.g. "#5865F2"
	// or "5865F2").
	Color *string `json:"color,omitempty"`
	// descriptionFormat is the template used to render the embed's
	// description. Supports the same placeholders as Format. Defaults to
	// "{{.Description}}".
	DescriptionFormat *string `json:"descriptionFormat,omitempty"`
	// authorName is shown on the embed's author line.
	AuthorName *string `json:"authorName,omitempty"`
	// footerText is shown in the embed's footer.
	FooterText *string `json:"footerText,omitempty"`
}

// EmbedSpecApplyConfiguration constructs a declarative configuration of the EmbedSpec type for use with
// apply.
func EmbedSpec() *EmbedSpecApplyConfiguration {
	return &EmbedSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *EmbedSpecApplyConfiguration) WithEnabled(value bool) *EmbedSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithColor sets the Color field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Color field is set to the value of the last call.
func (b *EmbedSpecApplyConfiguration) WithColor(value string) *EmbedSpecApplyConfiguration {
	b.Color = &value
	return b
}

// WithDescriptionFormat sets the DescriptionFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DescriptionFormat field is set to the value of the last call.
func (b *EmbedSpecApplyConfiguration) WithDescriptionFormat(value string) *EmbedSpecApplyConfiguration {
	b.DescriptionFormat = &value
	return b
}

// WithAuthorName sets the AuthorName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorName field is set to the value of the last call.
func (b *EmbedSpecApplyConfiguration) WithAuthorName(value string) *EmbedSpecApplyConfiguration {
	b.AuthorName = &value
	return b
}

// WithFooterText sets the FooterText field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FooterText field is set to the value of the last call.
func (b *EmbedSpecApplyConfiguration) WithFooterText(value string) *EmbedSpecApplyConfiguration {
	b.FooterText = &value
	return b
}
