/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FeedGroupStatusApplyConfiguration represents a declarative configuration of the FeedGroupStatus type for use
// with apply.
//
// FeedGroupStatus defines the observed state of a FeedGroup.
type FeedGroupStatusApplyConfiguration struct {
	// conditions represent the latest available observations of the FeedGroup's
	// overall state, following the standard Kubernetes condition conventions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// feeds is the observed status of every feed in Spec.Feeds, keyed by
	// RSSUrl.
	Feeds []FeedStatusApplyConfiguration `json:"feeds,omitempty"`
	// observedGeneration is the most recent generation observed for this FeedGroup
	// by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// FeedGroupStatusApplyConfiguration constructs a declarative configuration of the FeedGroupStatus type for use with
// apply.
func FeedGroupStatus() *FeedGroupStatusApplyConfiguration {
	return &FeedGroupStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FeedGroupStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *FeedGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithFeeds adds the given value to the Feeds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Feeds field.
func (b *FeedGroupStatusApplyConfiguration) WithFeeds(values ...*FeedStatusApplyConfiguration) *FeedGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFeeds")
		}
		b.Feeds = append(b.Feeds, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *FeedGroupStatusApplyConfiguration) WithObservedGeneration(value int64) *FeedGroupStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
