/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// FeedGroupSpecApplyConfiguration represents a declarative configuration of the FeedGroupSpec type for use
// with apply.
//
// FeedGroupSpec defines the desired state of a FeedGroup.
type FeedGroupSpecApplyConfiguration struct {
	// discordWebhookSecretRef points to the Secret containing the Discord webhook URL.
	// The secret must contain the webhook URL under the specified key.
	DiscordWebhookSecretRef *v1.SecretKeySelector `json:"discordWebhookSecretRef,omitempty"`
	// interval is the duration between feed checks (e.g., "30m", "1h"),
	// parsed by Go's time.ParseDuration. Must not be negative: a negative or
	// unreasonably short interval would requeue the FeedGroup in a tight
	// reconcile loop, hammering every feed host on each pass.
	Interval *string `json:"interval,omitempty"`
	// format is the default template for Discord messages.
	// Supports placeholders: {{.Title}}, {{.Description}}, {{.Link}}, {{.Published}}, {{.Author}}, {{.Categories}}.
	Format *string `json:"format,omitempty"`
	// embed configures Discord embed rendering, used as the default for all
	// feeds in this group unless a feed sets its own Embed.
	Embed *EmbedSpecApplyConfiguration `json:"embed,omitempty"`
	// username overrides the webhook's default display name for messages
	// sent from this group. Discord rejects names containing "clyde" or
	// "discord" (case-insensitive) or over 80 characters, so both
	// constraints are enforced here at admission rather than surfacing only
	// as a runtime send failure.
	Username *string `json:"username,omitempty"`
	// avatarURL overrides the webhook's default avatar for messages sent
	// from this group.
	AvatarURL *string `json:"avatarURL,omitempty"`
	// retries is the number of times to retry failed operations (fetch/send).
	Retries *int32 `json:"retries,omitempty"`
	// retryInterval is the duration between retries (e.g., "5m"), parsed by
	// Go's time.ParseDuration. Must not be negative: a negative or
	// unreasonably short interval would requeue the FeedGroup in a tight
	// reconcile loop, hammering every feed host on each pass.
	RetryInterval *string `json:"retryInterval,omitempty"`
	// feeds is the list of RSS feed configurations in this group. Capped at
	// maxConcurrentFetches (see feedgroup_controller.go) so a single
	// reconcile can't fan out an unbounded number of simultaneous outbound
	// fetches. RSS URLs must be unique within a group, since all per-feed
	// status (LastSeenEntry, LastSent, ETag, ...) is keyed by URL: two feeds
	// sharing a URL would silently clobber each other's status.
	Feeds []FeedSpecApplyConfiguration `json:"feeds,omitempty"`
	// catchUpLimit caps how many backlog entries are sent to Discord the
	// first time a feed is reconciled (i.e. before it has a recorded
	// LastSeenEntry). Without this, adding a feed with a long history
	// floods the webhook with every existing entry at once. Entries beyond
	// the limit are treated as already seen and are not sent.
	CatchUpLimit *int32 `json:"catchUpLimit,omitempty"`
}

// FeedGroupSpecApplyConfiguration constructs a declarative configuration of the FeedGroupSpec type for use with
// apply.
func FeedGroupSpec() *FeedGroupSpecApplyConfiguration {
	return &FeedGroupSpecApplyConfiguration{}
}

// WithDiscordWebhookSecretRef sets the DiscordWebhookSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiscordWebhookSecretRef field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithDiscordWebhookSecretRef(value v1.SecretKeySelector) *FeedGroupSpecApplyConfiguration {
	b.DiscordWebhookSecretRef = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithInterval(value string) *FeedGroupSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithFormat(value string) *FeedGroupSpecApplyConfiguration {
	b.Format = &value
	return b
}

// WithEmbed sets the Embed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Embed field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithEmbed(value *EmbedSpecApplyConfiguration) *FeedGroupSpecApplyConfiguration {
	b.Embed = value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithUsername(value string) *FeedGroupSpecApplyConfiguration {
	b.Username = &value
	return b
}

// WithAvatarURL sets the AvatarURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvatarURL field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithAvatarURL(value string) *FeedGroupSpecApplyConfiguration {
	b.AvatarURL = &value
	return b
}

// WithRetries sets the Retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retries field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithRetries(value int32) *FeedGroupSpecApplyConfiguration {
	b.Retries = &value
	return b
}

// WithRetryInterval sets the RetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryInterval field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithRetryInterval(value string) *FeedGroupSpecApplyConfiguration {
	b.RetryInterval = &value
	return b
}

// WithFeeds adds the given value to the Feeds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Feeds field.
func (b *FeedGroupSpecApplyConfiguration) WithFeeds(values ...*FeedSpecApplyConfiguration) *FeedGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFeeds")
		}
		b.Feeds = append(b.Feeds, *values[i])
	}
	return b
}

// WithCatchUpLimit sets the CatchUpLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CatchUpLimit field is set to the value of the last call.
func (b *FeedGroupSpecApplyConfiguration) WithCatchUpLimit(value int32) *FeedGroupSpecApplyConfiguration {
	b.CatchUpLimit = &value
	return b
}
