/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FeedStatusApplyConfiguration represents a declarative configuration of the FeedStatus type for use
// with apply.
//
// FeedStatus is the observed state of a single feed within a FeedGroup,
// keyed by RSSUrl. Consolidating what used to be seven parallel
// map[string]... fields on FeedGroupStatus (all keyed by the same URL) into
// one struct per feed means a feed's full health -- timestamps, retry
// count, and *why* it's failing -- reads as one coherent block in `kubectl
// get feedgroup -o yaml` instead of requiring cross-referencing seven maps
// by hand.
type FeedStatusApplyConfiguration struct {
	// conditions report this feed's health along the two independent
	// stages a delivery passes through: FeedConditionTypeReachable (was the
	// feed itself fetchable) and FeedConditionTypeDelivered (did rendering
	// and sending to Discord succeed). Each carries a machine-readable
	// Reason (e.g. "HTTP404", "Timeout", "WebhookInvalid") set by
	// internal/controller/classify.go, so a feed stuck on a permanent 404
	// is distinguishable at a glance from a misconfigured webhook, without
	// parsing LastError's free text.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// rssUrl identifies which feed (in FeedGroupSpec.Feeds) this status
	// corresponds to. Acts as the list-map merge key.
	RSSUrl *string `json:"rssUrl,omitempty"`
	// lastChecked is the last time this feed was successfully checked
	// (RFC3339 timestamp). A 304 or a fetch with no new entries still
	// counts as a successful check; a failed fetch does not advance it.
	LastChecked *string `json:"lastChecked,omitempty"`
	// lastSeenEntry is the last seen entry identifier (GUID or Link) for
	// this feed. Used to fetch only new entries after restarts.
	LastSeenEntry *string `json:"lastSeenEntry,omitempty"`
	// lastSent is a map of entry hash to timestamp (RFC3339), tracking
	// which entries have been sent to Discord to avoid duplicates.
	LastSent map[string]string `json:"lastSent,omitempty"`
	// lastError is the last error message encountered for this feed, from
	// whichever of fetch/render/send most recently failed. See Conditions
	// for a structured, machine-readable breakdown of which stage failed
	// and why.
	LastError *string `json:"lastError,omitempty"`
	// etag is the ETag header from this feed's last fetch. Sent back as
	// If-None-Match on the next fetch so an unchanged feed costs a 304
	// response instead of a full re-download and re-parse.
	ETag *string `json:"etag,omitempty"`
	// lastModified is the Last-Modified header from this feed's last fetch.
	// Sent back as If-Modified-Since on the next fetch, alongside ETag.
	LastModified *string `json:"lastModified,omitempty"`
	// retryCount is the number of consecutive retries since this feed last
	// succeeded.
	RetryCount *int32 `json:"retryCount,omitempty"`
	// backoffUntil is an RFC3339 timestamp before which this feed should not
	// be fetched again. Set on permanent fetch failures (e.g. HTTP 404) using
	// exponential backoff starting from Spec.RetryInterval; cleared on the
	// next successful fetch or when the FeedGroup spec changes. An empty
	// string means the feed is not in backoff.
	BackoffUntil *string `json:"backoffUntil,omitempty"`
}

// FeedStatusApplyConfiguration constructs a declarative configuration of the FeedStatus type for use with
// apply.
func FeedStatus() *FeedStatusApplyConfiguration {
	return &FeedStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FeedStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *FeedStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithRSSUrl sets the RSSUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RSSUrl field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithRSSUrl(value string) *FeedStatusApplyConfiguration {
	b.RSSUrl = &value
	return b
}

// WithLastChecked sets the LastChecked field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastChecked field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithLastChecked(value string) *FeedStatusApplyConfiguration {
	b.LastChecked = &value
	return b
}

// WithLastSeenEntry sets the LastSeenEntry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSeenEntry field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithLastSeenEntry(value string) *FeedStatusApplyConfiguration {
	b.LastSeenEntry = &value
	return b
}

// WithLastSent puts the entries into the LastSent field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the LastSent field,
// overwriting an existing map entries in LastSent field with the same key.
func (b *FeedStatusApplyConfiguration) WithLastSent(entries map[string]string) *FeedStatusApplyConfiguration {
	if b.LastSent == nil && len(entries) > 0 {
		b.LastSent = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.LastSent[k] = v
	}
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithLastError(value string) *FeedStatusApplyConfiguration {
	b.LastError = &value
	return b
}

// WithETag sets the ETag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ETag field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithETag(value string) *FeedStatusApplyConfiguration {
	b.ETag = &value
	return b
}

// WithLastModified sets the LastModified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastModified field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithLastModified(value string) *FeedStatusApplyConfiguration {
	b.LastModified = &value
	return b
}

// WithRetryCount sets the RetryCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryCount field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithRetryCount(value int32) *FeedStatusApplyConfiguration {
	b.RetryCount = &value
	return b
}

// WithBackoffUntil sets the BackoffUntil field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffUntil field is set to the value of the last call.
func (b *FeedStatusApplyConfiguration) WithBackoffUntil(value string) *FeedStatusApplyConfiguration {
	b.BackoffUntil = &value
	return b
}
