/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FeedSpecApplyConfiguration represents a declarative configuration of the FeedSpec type for use
// with apply.
//
// FeedSpec defines the configuration for a single RSS feed.
type FeedSpecApplyConfiguration struct {
	// rssUrl is the URL of the RSS feed to fetch. Only http:// and https:// are supported.
	RSSUrl *string `json:"rssUrl,omitempty"`
	// filter defines how to filter entries from this feed.
	Filter *FilterApplyConfiguration `json:"filter,omitempty"`
	// format is the template for Discord messages for this feed.
	// Overrides the group-level format if set.
	Format *string `json:"format,omitempty"`
	// embed configures Discord embed rendering for this feed. Overrides the
	// group-level Embed config if set.
	Embed *EmbedSpecApplyConfiguration `json:"embed,omitempty"`
	// forumThreadName creates a new forum post for each message, named from
	// this template, when DiscordWebhookSecretRef points at a forum
	// channel's webhook. Supports the same placeholders as Format. Leave
	// unset for regular text channels.
	ForumThreadName *string `json:"forumThreadName,omitempty"`
	// forumThreadID posts messages into an existing forum thread/post
	// instead of creating a new one. Takes precedence over ForumThreadName.
	ForumThreadID *string `json:"forumThreadID,omitempty"`
	// paused stops processing this feed if set to true.
	Paused *bool `json:"paused,omitempty"`
}

// FeedSpecApplyConfiguration constructs a declarative configuration of the FeedSpec type for use with
// apply.
func FeedSpec() *FeedSpecApplyConfiguration {
	return &FeedSpecApplyConfiguration{}
}

// WithRSSUrl sets the RSSUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RSSUrl field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithRSSUrl(value string) *FeedSpecApplyConfiguration {
	b.RSSUrl = &value
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithFilter(value *FilterApplyConfiguration) *FeedSpecApplyConfiguration {
	b.Filter = value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithFormat(value string) *FeedSpecApplyConfiguration {
	b.Format = &value
	return b
}

// WithEmbed sets the Embed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Embed field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithEmbed(value *EmbedSpecApplyConfiguration) *FeedSpecApplyConfiguration {
	b.Embed = value
	return b
}

// WithForumThreadName sets the ForumThreadName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForumThreadName field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithForumThreadName(value string) *FeedSpecApplyConfiguration {
	b.ForumThreadName = &value
	return b
}

// WithForumThreadID sets the ForumThreadID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForumThreadID field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithForumThreadID(value string) *FeedSpecApplyConfiguration {
	b.ForumThreadID = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *FeedSpecApplyConfiguration) WithPaused(value bool) *FeedSpecApplyConfiguration {
	b.Paused = &value
	return b
}
