name: E2E Tests

on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-e2e:
    permissions:
      contents: read
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go environment
        uses: ./.github/actions/setup-go-env

      - name: Lint Helm chart
        run: helm lint dist/chart

      - name: Running Test e2e
        run: mise run test-e2e
