name: Test Chart

on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-chart:
    permissions:
      contents: read
    name: Test Chart
    runs-on: ubuntu-latest
    env:
      IMG: controller:latest
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install_args: --locked

      - name: Create kind cluster
        run: kind create cluster

      - name: Build and load image
        run: |
          mise run docker-build
          kind load docker-image "${IMG}"

      - name: Lint Helm chart
        run: helm lint ./dist/chart

      - name: Deploy manager via Helm
        run: mise run helm-deploy

      - name: Check Helm release status
        run: mise run helm-status
